
const hasExtension = (fileName, extensions) => {
  return (new RegExp('(' + extensions.join('|').replace(/\./g, '\\.') + ')$', 'i')).test(fileName);
};

const removeExtension = (fileName, extensions) => {
  const regex = new RegExp('(' + extensions.join('|').replace(/\./g, '\\.') + ')$', 'i');
  return fileName.replace(regex, '');
};

const save = (code, name, type = 'text/plain') => {
  const blob = new Blob([code], { type });
  if (window.saveAs) {
    window.saveAs(blob, name);
  } else if(navigator.saveBlob) {
    navigator.saveBlob(blob, name);
  } else {
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download",name);
    const event = document.createEvent('MouseEvents');
    event.initMouseEvent('click', true, true, window, 1, 0, 0, 0, 0, false, false, false, false, 0, null);
    link.dispatchEvent(event);
  }
};

const saveAsMarkdown = (text, fileName) => {
  let name = fileName;
  if (!hasExtension(name, ['.md'])){
    name += '.md';
  }
  save(text, name, 'text/markdown');
};

const htmlTemplate = (title, styles, body) => {
  const stylesheets = styles.map(href => `<link rel="stylesheet" href="${href}" type="text/css">`).join('\n');

  return `
  <!doctype html>

  <html lang="en">
  <head>
  <meta charset="utf-8">

  <title>${title}</title>
  <meta name="description" content="This file was generated by Collaborizm React Markdown Editor">
  <meta name="author" content="Harsha Alva">

  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->

  ${stylesheets}

  <style type="text/css">
    body {
      padding: 40px 0;
    }
  </style>
  </head>

  <body>
  <div class="container">
  ${body}
  </div>
  </body>
  </html>`;
};

const saveAsHtml = (body, fileName) => {
  let name = fileName;
  let title = fileName;
  if (!hasExtension(name, ['.htm', '.html'])){
    name += '.html';
  } else {
    title = removeExtension(name, ['.htm', '.html']);
  }

  const styles = [
    'https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css',
    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css',
    'https://cdnjs.cloudflare.com/ajax/libs/prism/1.6.0/themes/prism-okaidia.css'
  ];

  const html = htmlTemplate(title, styles, body);
  save(html, name, 'text/html');
};

export { saveAsMarkdown, saveAsHtml };
